-- Seed ~35 UK-relevant industries for sticker/label buyers
INSERT INTO industries (slug, name, parent_id) VALUES
('food-beverage', 'Food & Beverage', NULL),
('breweries', 'Breweries', 1),
('coffee-roasters', 'Coffee Roasters', 1),
('bakeries', 'Bakeries', 1),
('hot-sauce', 'Hot Sauce Makers', 1),
('health-beauty', 'Health & Beauty', NULL),
('candle-makers', 'Candle Makers', 6),
('soap-makers', 'Soap Makers', 6),
('skincare', 'Skincare Brands', 6),
('haircare', 'Haircare Brands', 6),
('home-garden', 'Home & Garden', NULL),
('plant-shops', 'Plant Shops', 11),
('home-decor', 'Home Decor', 11),
('garden-centres', 'Garden Centres', 11),
('fashion-accessories', 'Fashion & Accessories', NULL),
('jewellery', 'Jewellery Makers', 15),
('clothing-brands', 'Clothing Brands', 15),
('bag-makers', 'Bag & Luggage Makers', 15),
('pets', 'Pets', NULL),
('pet-food', 'Pet Food Brands', 19),
('pet-accessories', 'Pet Accessories', 19),
('tech-gadgets', 'Tech & Gadgets', NULL),
('electronics', 'Electronics Brands', 22),
('phone-accessories', 'Phone Accessories', 22),
('stationery-paper', 'Stationery & Paper Goods', NULL),
('greeting-cards', 'Greeting Card Makers', 25),
('planners', 'Planner & Journal Brands', 25),
('art-craft', 'Art & Craft Supplies', NULL),
('etsy-sellers', 'Etsy Sellers', 28),
('craft-kits', 'Craft Kit Brands', 28),
('events-weddings', 'Events & Weddings', NULL),
('wedding-stationery', 'Wedding Stationery', 31),
('event-planners', 'Event Planners', 31),
('fitness-sports', 'Fitness & Sports', NULL),
('supplement-brands', 'Supplement Brands', 34),
('sports-gear', 'Sports Gear', 34),
('fba-sellers', 'Amazon FBA Sellers', NULL),
('subscription-boxes', 'Subscription Box Brands', NULL)
ON CONFLICT (slug) DO NOTHING;
